### ISSUE TITLE
Add option to assign secret used in onboarding as device secret

### ISSUE THREAD

**Issue by susanhooks** [nautobot/nautobot-app-device-onboarding#133]
### Environment
* Nautobot version:  2.0.5
* nautobot-device-onboarding version: 2.0.2

I would like an optional functionality to assign the secret group used in the onboarding process, as the secret group on the device, if created. 

### Proposed Functionality

Via plugin config settings, be able to assign set_secret_group = True, and have the secret group that was used when onboarding the device assigned to the device. 

### Use Case
It makes sense to me that if the secret group is successful in onboarding, that you should be able to have it assigned automatically if desired. Saves me a few clicks after onboarding.

**Comment by whitej6** [comment]
Great idea!!!  Should just be a Boolean var on the job and the assignment in the create.

**Comment by susanhooks** [comment]
Submitted PR for this #140 functionality.

**Comment by scetron** [comment]
Closed by #140
