### ISSUE TITLE
Plugin doesn't show up in Swagger

### ISSUE THREAD

**Issue by aj-cruz** [nautobot/nautobot-app-device-onboarding#142]
### Environment
* Python version:  3.11.7
* Nautobot version:  2.0.6
* nautobot-device-onboarding version:  3.0.1

### Expected Behavior
When navigating to API Documentation, /plugins/device-onboarding available to view API viewsets

### Observed Behavior
Device Onboarding is not listed

### Steps to Reproduce
1. Click the "API" link at the bottom of the Nautobot GUI
2. CTRL+F and search for "onboarding" or scroll to /plugins/ and manually search for device onboarding

**Comment by scetron** [comment]
Hello @aj-cruz Thanks for the issue. I believe that this is due to moving the plugin to a job. It should be available via the jobs API. I will update the documentation.
