### ISSUE TITLE
DNAC & ACI onboarding issue from nautobot

### ISSUE THREAD

**Issue by ShivaniMauryaIntel** [nautobot/nautobot-app-device-onboarding#187]
### Environment
* Python version:  3.8.0
* Nautobot version:  2.1.8

Onboarding successful for DNAC & ACI using Device Onboarding job

Getting Error reading SSH protocol banner

### Steps to Reproduce
1. Run "Device Onboarding" job from Nautobot UI with port 443
![Nautobot Onboarding Error](https://github.com/nautobot/nautobot-app-device-onboarding/assets/107266238/3e96692e-a0ca-4e55-b94c-c305b0acb750)

**Comment by mzbroch** [comment]
Please see SSOT App for Cisco ACI : https://docs.nautobot.com/projects/ssot/en/latest/user/integrations/aci/

**Comment by ShivaniMauryaIntel** [comment]
I followed the document, however, I do not see any Data Sources available –
***@***.***
FYI – I have SSOT plugin already installed.

Regards,
Shivani Maurya

**Comment by scetron** [comment]
Hello Shivani, the Onboarding plugin is not meant to onboard controller based devices. For ACI and DNAC, please see the SSoT Plugin which works independently of the device onboarding plugin. If you have issues with that plugin, please open an issue under that repo.

**Comment by ShivaniMauryaIntel** [comment]
Hi Stephen,

I have opened the issue #465.

Regards,
Shivani Maurya
