### ISSUE TITLE
Allow onboarding to use CredentialsEnvVars

### ISSUE THREAD

**Issue by nathanielfernandez** [nautobot/nautobot-app-device-onboarding#208]
### Environment
* Nautobot version:  2.2.8
* nautobot-device-onboarding version:  4.0.0rc2

### Proposed Functionality
It seems 4.0.0rc2 is only expecting Nautobot Secrets credential type. We use CredentialsEnvVars and to be able to use the new version of device onboarding, we would need to make updates to our credential type to make it work. If possible, I'd like to request to make the new onboarding usable for CredentialsEnvVars too.

### Use Case
This would be useful for setups that use the CredentialsEnvVars.

**Comment by scetron** [comment]
Hello! Thanks for opening the issue. Are you using the credential with sync devices or sync network data? If using it for sync devices, you should be able to leverage secrets by specifying the secret as an env var, this will automatically place the secret on the newly onboarded device.

**Comment by nathanielfernandez** [comment]
I just tried to move credential types from CredentialsEnvVars to Nautobot Secrets in lab and in QA. Actually it's not as hard as I thought it would be. Just had to wait a long time while the secrets groups is associated with the device objects.

**Comment by scetron** [comment]
I am glad that helps! I am going to close this issue for now, as I believe that all secrets should be going through the secrets objects now.
