### ISSUE TITLE
Device Onboarding 4.0 is Not Compatible with Latest Secrets Providers

### ISSUE THREAD

**Issue by bryanculver** [nautobot/nautobot-app-device-onboarding#217]
This wasn't present in 3.0.1 of Device Onboarding:

https://github.com/nautobot/nautobot-app-device-onboarding/blob/995c73906a7850f71faa7ab4108c541c1ec1783a/pyproject.toml#L37

Secrets Providers is already on 3.1: https://github.com/nautobot/nautobot-app-secrets-providers/releases

**Comment by scetron** [comment]
@jeffkala any issue with moving this to *?

**Comment by jeffkala** [comment]
> @jeffkala any issue with moving this to *?

No issues that I'm aware of.

**Comment by bryanculver** [comment]
> > @jeffkala any issue with moving this to *?
> 
> No issues that I'm aware of.

I am not finding in the code where `nautobot_secrets_providers` is imported from directly. Is it even required?

The framework for Secrets is provided by Core itself.

**Comment by Dav-C** [comment]
I suspect this was used in testing but not intended to be in the final release.

**Comment by nkallergis** [comment]
Adding a PR for Secrets Provider in order to resolve dependency issue: https://github.com/nautobot/nautobot-app-secrets-providers/pull/146
