### ISSUE TITLE
Let's cut a 4.0.2 release to fix compatitability with nautobot-ssot

### ISSUE THREAD

**Issue by mattmiller87** [nautobot/nautobot-app-device-onboarding#246]
https://github.com/nautobot/nautobot-app-device-onboarding/blob/fd8bb85dcc6290374df2ae2bec998c38f9dd370b/pyproject.toml#L34

Failing with Nautobot-SSOT `v3.1.0` - https://github.com/nautobot/nautobot-app-ssot/releases

```
Updating dependencies
Resolving dependencies...


Because nautobot-device-onboarding (4.0.1) depends on nautobot-ssot (>=2.6.0,<3.0.0)
 and nautobot-ssot[all] (3.1.0) depends on nautobot-ssot (3.1.0), nautobot-device-onboarding (4.0.1) is incompatible with nautobot-ssot[all] (3.1.0).
So, because nautobot-ntc-managed-services depends on both nautobot-device-onboarding (4.0.1) and nautobot-ssot[all] (3.1.0), version solving failed.
```

**Comment by alhogan** [comment]
Ah, it looks like all the required updates have been made already.

**Comment by scetron** [comment]
We're probably going to cut a new release shortly, but a lot of users that rely on DO also have many SSoT plugins that have not necessarily been updated yet.

**Comment by susanhooks** [comment]
SSoT v3 support added #258
