### ISSUE TITLE
When an auth or timeout failure happens each subtask still runs

### ISSUE THREAD

**Issue by jeffkala** [nautobot/nautobot-app-device-onboarding#255]
### Environment
* Python version:  3.11
* Nautobot version:  2.2
* nautobot-device-onboarding version: 4.0.1
* ntc-templates version: 6.0

### Expected Behavior
Might be solved by a connectivity check; however, if a timeout happens on the first command execution for timeout or auth failure all subsequent commands shouldn't be attempted as it causes unnecessary failures and login attempts.

### Observed Behavior
If auth fails, it tries to login and run `show version`, and then even if auth fails on the first command it does the same for the remaining commands.

### Steps to Reproduce
1. Run sync devices job on with purposefully bad credentials
2. Will see the same auth failure occur for every command.

Probably makes sense here to add a connecitivyt check + logic to say if the first command fails with (timeout, auth) to stop and don't runn the other commands.

Potentially create our own connection handling on the nornir side.

**Comment by scetron** [comment]
Fixed by #280
