### ISSUE TITLE
Many logs are getting incorrectly caught by a no platform set error

### ISSUE THREAD

**Issue by jeffkala** [nautobot/nautobot-app-device-onboarding#279]
### Environment
* Python version: 3.11
* Nautobot version:  2.2
* nautobot-device-onboarding version:  4.1.0
* ntc-templates version: 6.0

### Expected Behavior
Proper execption logging getting bubbled up to user.

### Observed Behavior

certain logs are getting caught by a generic platform not set log, which is hiding the actual failure reason.

### Steps to Reproduce
1.
2.
3.

**Comment by scetron** [comment]
Fixed by #280
