### ISSUE TITLE
Using the Plugin with napalm and netmiko extras for Jump Host does not work

### ISSUE THREAD

**Issue by thomas-rotszyld** [nautobot/nautobot-app-device-onboarding#43]
### Environment
* Python version:  3.9.10
* Nautobot version:  1.2.8
* nautobot-device-onboarding version:  1.1.1

### Steps to Reproduce
1. Define a ssh config file to use a jump host for ssh connection 
{
    "conn_timeout": 15,
    "ssh_config_file": "/opt/nautobot/.ssh/napalm.config"
}
                        
2. Onboard a device

### Expected Behavior
SSH Connection through the JUMP Host should work

### Observed Behavior
SSH Connection does not work.

**Comment by thomas-rotszyld** [comment]
https://github.com/nautobot/nautobot-plugin-device-onboarding/blob/develop/nautobot_device_onboarding/netdev_keeper.py#L230

Check Reachability Method use socket to check the reachability.. with not using NAPALM Extras for SSH Connection.
Device is "seen" as unreachable.

Suggestion: Pass a flag True/False to have the possibility to skip the reachability step.

**Comment by jeffkala** [comment]
Don't think we will support this in the old version of the app being <4.0.  In 4 this is working now (welll once we put out 4.2) via 
```python
PLUGINS_CONFIG = {
    "nautobot_device_onboarding": {},
    "nautobot_ssot": {
        "hide_example_jobs": is_truthy(os.getenv("NAUTOBOT_SSOT_HIDE_EXAMPLE_JOBS")),
    },
    "nautobot_plugin_nornir": {
        "nornir_settings": {
            "credentials": "nautobot_plugin_nornir.plugins.credentials.nautobot_secrets.CredentialsNautobotSecrets",
            "runner": {
                "plugin": "threaded",
                "options": {
                    "num_workers": 20,
                },
            },
        },
        "connection_options": {
            "netmiko": {
                "extras": {
                    "ssh_config_file": "/root/.ssh/config",
                },
            },
        },
    },
}
```
