### ISSUE TITLE
Integration of Network Importer

### ISSUE THREAD

**Issue by jvanderaa** [nautobot/nautobot-app-device-onboarding#57]
### Environment
* Nautobot version:  
* nautobot-device-onboarding version:  

### Proposed Functionality

Merge in functionality of Network Importer into this project.

## Implementation Planning

The current state is to look to add an independent job(s) into this plugin that will handle the functionality that Network Importer was providing as an independent project. The current set up within Device Onboarding into Nautobot does an excellent job and the initiative will not change this.

- [x] Create Nautobot DiffSync object to handle writing of the data to Nautobot
- [ ] Gather data from network devices in a consistent fashion, today within Network Importer data is gathered from various sources including Netmiko, NAPALM, Configuration sent to Batfish
- [ ] Remove dependency on pyATS to be able to support onboarding of more device types. pyATS was used primarily in parsing output of `show lldp/cdp neighbor` output. This would put the data into a nested dictionary output. This will be swapped out with using NTC Templates and Netmiko, both standardized methods of getting command output into a structured format. For devices that have JSON output of these items, a flattener will be needed
- [ ] More to complete the process

### Use Case

Migrating to a single installed platform will ease the onboarding process and help to get to automating with the data sooner!

**Comment by scetron** [comment]
I propose also the following quality of life features to be fleshed out if necessary:

[ ] Batching system. Outside of filters to limit what is onboarded, limit number of devices that will be onboarded at one time. This limit is necessary to review what has been onboarded and to limit total imports for a single run beyond what a dynamic group may provide.

[ ] Ability to mark failures in onboarding and to rerun subset of failed devices from a given job.

**Comment by mzbroch** [comment]
1. This issue documents the "implement plan", but not the feature thus I think we have no visibility into what's being planned.
2. What is the exact feature planned for onboarding ?
3. How this will impact onboarding inputs and onboaring results?
4. What is the impact of network-importer ?
5. What are the breaking changes to both?
6. Is the parity planned between both network-importer and device-onboarding ?

**Comment by chadell** [comment]
This could be a good opportunity to create an ADR record, to explain the overall approach.

**Comment by cmong-nextech** [comment]
Do we know if there is a roadmap or progress on this? Now that the Network Importer plugin doesn't work with the latest nautobot this would be a fantastic feature to add here.

**Comment by scetron** [comment]
Hello@cmong-nextech. This is being executed toward the end of January with a slightly different plan, but the functionality will be the same (importing interfaces and other data in Nautobot). More information will be added closer to release.

**Comment by logix-bfarrington** [comment]
It is the end of January and I see version 2.1.2 is now out, but I don't see anything regarding network importer in the change logs. Is there any update on when this new functionality is planned to be released?

**Comment by scetron** [comment]
Yes, the work is in progress now. I can't commit to an exact release date, but it is a high priority for us.

**Comment by scetron** [comment]
Closed by #214
