### ISSUE TITLE
Onboarding Aruba Switches

### ISSUE THREAD

**Issue by quistian** [nautobot/nautobot-app-device-onboarding#84]
### Environment
* Nautobot version:  1.5.11
* nautobot-device-onboarding version:  1.1.2

### Proposed Functionality
I don't see any napalm plugins for Aruba devices, either running AOS or CX-AOS.
And I was not sure either about Cisco IOS-XE
Are there plans for these?

**Comment by scetron** [comment]
Hello! I believe that IOS-XE should work with the IOS drivers (as I don't believe the syntax is very different?). 

For Aruba devices, you may want to check out this driver: https://github.com/napalm-automation-community/napalm-arubaos-switch

**Comment by quistian** [comment]
Great.... I will test that out natively. Once I see how it works, is there something special I have to do to add it to my nautobot system? Do I just repeat what I did in my own python venv?

**Comment by scetron** [comment]
I don't believe there is anything special with adding the particular library, so you should be able to follow the steps similar to what you do in your own venv in the Nautobot env/venv. 

You will then follow then add a napalm mapping for the particular module here: https://docs.nautobot.com/projects/device-onboarding/en/latest/admin/install/#app-configuration:~:text=onboarding_extensions_map

**Comment by quistian** [comment]
Done all of that. Almost got the onboarding done of one device. Where do I find the napalm options to ignore certificate/ssl errors?

**Comment by scetron** [comment]
> Done all of that. Almost got the onboarding done of one device. Where do I find the napalm options to ignore certificate/ssl errors?

You should be able to put these options in napalm_args in the Plugin settings.

> I am also having problems onboarding with a paramiko related known_hosts error:
> 
> OnboardException: fail-connect: ERROR: A paramiko SSHException occurred during connection creation: Server '10.6.0.84' not found in known_hosts
> 
> In fact this host does have an entry in /opt/nautobot/.ssh/known_hosts. It was put there when I manually sshed to the switch at 10.6.0.84

You might need to also place this in the Worker. If that doesn't work, I would try to make sure it is in fact using that known_hosts file path (I would need to double check).

**Comment by scetron** [comment]
@quistian, did that work out or are you still having any trouble?

**Comment by Manchuker1120** [comment]
PLUGINS_CONFIG = {
    "nautobot_plugin_nornir": {
        "nornir_settings": {
            "credentials": "nautobot_plugin_nornir.plugins.credentials.settings_vars.CredentialsSettingsVars",
                },
        "username":"admin",
        "password":"Wg(00)Sx[00]",
        "dispatcher_mapping": {
            "junos":"nornir_nautobot.plugins.tasks.dispatcher.default.NetmikoNautobotNornirDriver",
            "a10": "nornir_nautobot.plugins.tasks.dispatcher.default.NetmikoNautobotNornirDriver",
            },
         },
    "nautobot_golden_config": {
        "per_feature_bar_width": 0.15,
        "per_feature_width": 13,
        "per_feature_height": 4,
        "enable_backup": True,
        "enable_compliance": True,
        "enable_intended": True,
        "enable_sotagg": True,
        "sot_agg_transposer": None,
        "enable_postprocessing": False,
        "postprocessing_callables": [],
        "postprocessing_subscribed": [],
        "platform_slug_map": None,
        # "get_custom_compliance": "my.custom_compliance.func"
    },
    "nautobot_device_onboarding": {
        "platform_map":{
            "a10": "a10",
            "juniper_screenos": "junos",
            },
        },
    }
[Message]Cannot import "a10". Is the library installed?

**Comment by scetron** [comment]
We've moved over to a new methodology and I believe supporting aruba will be easier with this new technique, although it will have to be added.
