### ISSUE TITLE
Prometheus metrics for netdev_keeper

### ISSUE THREAD

**Issue by davidban77** [nautobot/nautobot-app-device-onboarding#85]
### Environment
* Nautobot version:  1.5.13 (to get `metrics.py` support)
* nautobot-plugin-device-onboarding version:  latest

### Proposed Functionality

Expose Prometheus metrics for this app. Examples:

#### Check Reachability and Netmiko calls

In modules like [`netdev_keeper`](https://github.com/nautobot/nautobot-plugin-device-onboarding/blob/develop/nautobot_device_onboarding/netdev_keeper.py#L107) there _could_ be value exposing metrics regarding the amount of time `check_reachability` has been called or even `guess_device_type` has been called or returned errors:

- `nautobot_device_onboarding_reachability_ok_total 27.0` 
- `nautobot_device_onboarding_reachability_failed_total 3.0` 
- `nautobot_guess_device_type_total{guessed_device_type="cisco_xr"} 2.0`
- `nautobot_guess_device_type_errors_total{error_code="NetMikoAuthenticationException"} 2.0`

These are just a few examples.

### Use Case

Allow users of the platform to generate time series from their Nautobot instance. In the end this could troubleshoot and get more insight of their Nautobot platform.

**Comment by scetron** [comment]
Some metrics exist already, but netdevkeeper run on the worker.

**Comment by scetron** [comment]
Closing this for now, will reopen later if applicable.
