### ISSUE TITLE
Device Onboarding NAPALM credentials not working

### ISSUE THREAD

**Issue by scetron** [nautobot/nautobot-app-device-onboarding#90]
### Environment
* Python version:  x
* Nautobot version: 1.15
* nautobot-device-onboarding version:  latest

### Steps to Reproduce
1. Use NAUTOBOT_NAPALM_USERNAME and NAUTOBOT_NAPALM_PASSWORD in the Config
2. Try to onboard a device using the plugin
3. Get an error

### Expected Behavior
Onboard Device

### Observed Behavior
Error

**Comment by scetron** [comment]
As a workaround, add in `NAPALM_USERNAME=$NAUTOBOT_NAPALM_USERNAME` and `NAPALM_PASSWORD=$NAUTOBOT_NAPALM_PASSWORD` to the environment or `nautobot_settings.py`

**Comment by modonovan** [comment]
I spotted this using the docker-compose deployment with plugins Dockerfile as per https://github.com/nautobot/nautobot-docker-compose/blob/main/docs/plugins.md.

This can be worked around in this setting by configuring your `local.env` file as such:

```
NAUTOBOT_NAPALM_USERNAME=some-user
NAUTOBOT_NAPALM_PASSWORD=something-secure-of-your-choosing
NAPALM_USERNAME=$NAUTOBOT_NAPALM_USERNAME
NAPALM_PASSWORD=$NAUTOBOT_NAPALM_PASSWORD
```

And your `nautobot_config.py` should look like:

```
# Credentials that Nautobot will uses to authenticate to devices when connecting via NAPALM.
NAPALM_USERNAME = os.getenv("NAUTOBOT_NAPALM_USERNAME", "")
NAPALM_PASSWORD = os.getenv("NAUTOBOT_NAPALM_PASSWORD", "")
```

**Comment by scetron** [comment]
Closing as Device Onboarding now relies on other mechanisms to get credentials.
